# Generated by Django 5.0.3 on 2024-03-29 19:02

import mdeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=mdeditor.fields.MDTextField(),
        ),
        migrations.AlterField(
            model_name='problems',
            name='problem_description',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
