# Generated by Django 5.0.3 on 2024-03-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_problems_firstname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problems',
            name='product',
        ),
        migrations.RemoveField(
            model_name='problems',
            name='user',
        ),
        migrations.AddField(
            model_name='problems',
            name='email',
            field=models.EmailField(default=2, max_length=254),
            preserve_default=False,
        ),
    ]
