# Generated by Django 5.0.3 on 2024-03-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureditems',
            name='chegirma',
            field=models.CharField(max_length=20),
        ),
    ]
