# Generated by Django 5.0.3 on 2024-03-29 18:59

import mdeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
