# Generated by Django 5.0.3 on 2024-03-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_featureditems_chegirma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/my_pic'),
        ),
    ]
